### ISSUE TITLE
Genesis Alpha Proposals not rendering 

### ISSUE THREAD

**Issue by markspereira** [alicedapp/AliceX#28]
![image](https://user-images.githubusercontent.com/17998913/65378569-5f281180-dcba-11e9-8ae8-79f7bcf566f2.png)
Proposals not rendering in Genesis Alpha DAO really crucial issue as Genesis Alpha is our corner stone :)

**Comment by mrrobot16** [comment]
I found the problem for this issue, its because the server is not returning Genesis Alpha proposals with the stage of value "Queued" or "Boosted". When you go to another dao like dxDao it does return proposal with the stage value as "Queued" and "Boosted". I believe its a server problem.

**Comment by mrrobot16** [comment]
Genesis Alpha is not the only one with problems. I think its because the server is limiting the amount of proposals to about 100, so if a DAO has had more than 100 proposals passed or not then the server is giving us only the first 100 proposals versus giving us ALL proposals so that it becomes on our end to filter of All Proposals that are recently added or in "Queued" or "Boosted". I am almost certain the problem is on the server call. Server is giving only first ever 100 proposals per DAO.
